COMPANIES = [
    # === Workday API (confirmed working) ===
    {
        "name": "Barclays",
        "scraper_type": "workday",
        "base_url": "https://barclays.wd3.myworkdayjobs.com/en-US/external_career_site_barclays",
        "wday_path": "barclays/external_career_site_barclays",
    },
    {
        "name": "Morgan Stanley",
        "scraper_type": "workday",
        "base_url": "https://ms.wd5.myworkdayjobs.com/External",
        "wday_path": "ms/External",
    },
    {
        "name": "Citi",
        "scraper_type": "workday",
        "base_url": "https://citi.wd5.myworkdayjobs.com/2",
        "wday_path": "citi/2",
    },
    {
        "name": "Fidelity International",
        "scraper_type": "workday",
        "base_url": "https://fil.wd3.myworkdayjobs.com/001",
        "wday_path": "fil/001",
    },
    {
        "name": "Nomura",
        "scraper_type": "workday",
        "base_url": "https://nomuracareers.wd1.myworkdayjobs.com/en-US/NomuraExternalCareers",
        "wday_path": "nomuracareers/NomuraExternalCareers",
    },
    {
        "name": "Macquarie",
        "scraper_type": "workday",
        "base_url": "https://macquarie.wd3.myworkdayjobs.com/en-US/Macquarie_Careers",
        "wday_path": "macquarie/Macquarie_Careers",
    },
    {
        "name": "Credit Suisse (UBS)",
        "scraper_type": "workday",
        "base_url": "https://ubs.wd3.myworkdayjobs.com/en-US/Find_a_job_at_UBS",
        "wday_path": "ubs/Find_a_job_at_UBS",
    },

    # === Custom HTML / SPA scrapers ===
    # These sites are JS-rendered SPAs - the scraper will attempt HTML parsing
    # but most results will come from the aggregators (LinkedIn, Indeed)
    {
        "name": "Societe Generale",
        "scraper_type": "custom_html",
        "base_url": "https://careers.societegenerale.com/en/job-offers",
        "search_url": "https://careers.societegenerale.com/en/job-offers",
    },
    {
        "name": "BNP Paribas",
        "scraper_type": "custom_html",
        "base_url": "https://group.bnpparibas/emploi-carriere/toutes-offres-emploi",
        "search_url": "https://group.bnpparibas/emploi-carriere/toutes-offres-emploi",
    },
    {
        "name": "Natixis",
        "scraper_type": "custom_html",
        "base_url": "https://recrutement.natixis.com",
        "search_url": "https://recrutement.natixis.com",
    },
    {
        "name": "CACIB",
        "scraper_type": "custom_html",
        "base_url": "https://careers.ca-cib.com/offres-emploi",
        "search_url": "https://careers.ca-cib.com/offres-emploi",
    },
    {
        "name": "Goldman Sachs",
        "scraper_type": "custom_html",
        "base_url": "https://higher.gs.com/results",
        "search_url": "https://higher.gs.com/results",
    },
    {
        "name": "JP Morgan",
        "scraper_type": "custom_html",
        "base_url": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs",
        "search_url": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs",
    },
    {
        "name": "Lazard",
        "scraper_type": "custom_html",
        "base_url": "https://lazard-careers.tal.net/vx/lang-en-GB/appcentre-ext/brand-4/candidate/jobboard/vacancy/2/adv/",
        "search_url": "https://lazard-careers.tal.net/vx/lang-en-GB/appcentre-ext/brand-4/candidate/jobboard/vacancy/2/adv/",
    },
    {
        "name": "Deutsche Bank",
        "scraper_type": "custom_html",
        "base_url": "https://careers.db.com/professionals/search-roles",
        "search_url": "https://careers.db.com/professionals/search-roles",
    },
    {
        "name": "Murex",
        "scraper_type": "custom_html",
        "base_url": "https://www.murex.com/careers",
        "search_url": "https://www.murex.com/careers",
    },
    {
        "name": "Kepler Cheuvreux",
        "scraper_type": "custom_html",
        "base_url": "https://www.keplercheuvreux.com/en/careers",
        "search_url": "https://www.keplercheuvreux.com/en/careers",
    },
    {
        "name": "Rothschild & Co",
        "scraper_type": "custom_html",
        "base_url": "https://www.rothschildandco.com/en/careers/",
        "search_url": "https://www.rothschildandco.com/en/careers/",
    },
    {
        "name": "HSBC",
        "scraper_type": "custom_html",
        "base_url": "https://www.hsbc.com/careers/students-and-graduates",
        "search_url": "https://www.hsbc.com/careers/students-and-graduates",
    },
    {
        "name": "UBS",
        "scraper_type": "custom_html",
        "base_url": "https://www.ubs.com/global/en/careers/students.html",
        "search_url": "https://www.ubs.com/global/en/careers/students.html",
    },
    {
        "name": "Bank of America",
        "scraper_type": "custom_html",
        "base_url": "https://campus.bankofamerica.com/careers",
        "search_url": "https://campus.bankofamerica.com/careers",
    },
    # === Additional banks - Finance de Marché ===
    {
        "name": "Cantor Fitzgerald",
        "scraper_type": "custom_html",
        "base_url": "https://www.cantorfitzgerald.com/careers",
        "search_url": "https://www.cantorfitzgerald.com/careers",
    },
    {
        "name": "Jefferies",
        "scraper_type": "custom_html",
        "base_url": "https://www.jefferies.com/careers/",
        "search_url": "https://www.jefferies.com/careers/",
    },
    {
        "name": "Standard Chartered",
        "scraper_type": "custom_html",
        "base_url": "https://www.sc.com/en/careers/",
        "search_url": "https://www.sc.com/en/careers/",
    },
    {
        "name": "Credit Mutuel CIC",
        "scraper_type": "custom_html",
        "base_url": "https://www.creditmutuel.com/fr/recrutement.html",
        "search_url": "https://www.creditmutuel.com/fr/recrutement.html",
    },
    {
        "name": "Commerzbank",
        "scraper_type": "custom_html",
        "base_url": "https://jobs.commerzbank.com/",
        "search_url": "https://jobs.commerzbank.com/",
    },
    {
        "name": "ING",
        "scraper_type": "custom_html",
        "base_url": "https://www.ing.jobs/global/en.htm",
        "search_url": "https://www.ing.jobs/global/en.htm",
    },
    {
        "name": "ABN AMRO",
        "scraper_type": "custom_html",
        "base_url": "https://www.abnamro.com/en/careers",
        "search_url": "https://www.abnamro.com/en/careers",
    },
    {
        "name": "Exane (BNP Paribas)",
        "scraper_type": "custom_html",
        "base_url": "https://www.exane.com/en/careers/",
        "search_url": "https://www.exane.com/en/careers/",
    },
    {
        "name": "Millennium Management",
        "scraper_type": "custom_html",
        "base_url": "https://www.mlp.com/careers/",
        "search_url": "https://www.mlp.com/careers/",
    },
    {
        "name": "Citadel Securities",
        "scraper_type": "custom_html",
        "base_url": "https://www.citadelsecurities.com/careers/",
        "search_url": "https://www.citadelsecurities.com/careers/",
    },
    {
        "name": "Jane Street",
        "scraper_type": "custom_html",
        "base_url": "https://www.janestreet.com/join-jane-street/open-roles/",
        "search_url": "https://www.janestreet.com/join-jane-street/open-roles/",
    },
    {
        "name": "Optiver",
        "scraper_type": "custom_html",
        "base_url": "https://optiver.com/working-at-optiver/career-opportunities/",
        "search_url": "https://optiver.com/working-at-optiver/career-opportunities/",
    },
    {
        "name": "Qube Research & Technologies",
        "scraper_type": "custom_html",
        "base_url": "https://www.qube-rt.com/careers/",
        "search_url": "https://www.qube-rt.com/careers/",
    },
    {
        "name": "Euronext",
        "scraper_type": "custom_html",
        "base_url": "https://www.euronext.com/en/careers",
        "search_url": "https://www.euronext.com/en/careers",
    },
    {
        "name": "Amundi",
        "scraper_type": "custom_html",
        "base_url": "https://careers.amundi.com/",
        "search_url": "https://careers.amundi.com/",
    },
    {
        "name": "AXA Investment Managers",
        "scraper_type": "custom_html",
        "base_url": "https://www.axa-im.com/careers",
        "search_url": "https://www.axa-im.com/careers",
    },
    {
        "name": "Ostrum Asset Management (Natixis)",
        "scraper_type": "custom_html",
        "base_url": "https://www.ostrum.com/en/careers",
        "search_url": "https://www.ostrum.com/en/careers",
    },
    {
        "name": "Mediobanca",
        "scraper_type": "custom_html",
        "base_url": "https://www.mediobanca.com/en/careers.html",
        "search_url": "https://www.mediobanca.com/en/careers.html",
    },
    {
        "name": "Unicredit",
        "scraper_type": "custom_html",
        "base_url": "https://www.unicreditgroup.eu/en/careers.html",
        "search_url": "https://www.unicreditgroup.eu/en/careers.html",
    },
    {
        "name": "Oddo BHF",
        "scraper_type": "custom_html",
        "base_url": "https://www.oddo-bhf.com/en/careers/",
        "search_url": "https://www.oddo-bhf.com/en/careers/",
    },
    {
        "name": "Berenberg",
        "scraper_type": "custom_html",
        "base_url": "https://www.berenberg.com/en/careers",
        "search_url": "https://www.berenberg.com/en/careers",
    },
    # === From Dauphine césure CSVs - Finance de Marché ===
    {
        "name": "BRED Banque Populaire",
        "scraper_type": "custom_html",
        "base_url": "https://www.bred.fr/nous-rejoindre",
        "search_url": "https://www.bred.fr/nous-rejoindre",
    },
    {
        "name": "La Banque Postale",
        "scraper_type": "custom_html",
        "base_url": "https://www.labanquepostale.com/carrieres",
        "search_url": "https://www.labanquepostale.com/carrieres",
    },
    {
        "name": "Banque de France",
        "scraper_type": "custom_html",
        "base_url": "https://www.banque-france.fr/recrutement",
        "search_url": "https://www.banque-france.fr/recrutement",
    },
    {
        "name": "Coface",
        "scraper_type": "custom_html",
        "base_url": "https://www.coface.com/careers",
        "search_url": "https://www.coface.com/careers",
    },
    {
        "name": "SILEX Investment Partners",
        "scraper_type": "custom_html",
        "base_url": "https://www.silex-ip.com/careers",
        "search_url": "https://www.silex-ip.com/careers",
    },
    {
        "name": "Feefty",
        "scraper_type": "custom_html",
        "base_url": "https://www.feefty.com/careers",
        "search_url": "https://www.feefty.com/careers",
    },
    {
        "name": "Market Securities",
        "scraper_type": "custom_html",
        "base_url": "https://www.marketsecurities.com/careers",
        "search_url": "https://www.marketsecurities.com/careers",
    },
    {
        "name": "Magen Financial",
        "scraper_type": "custom_html",
        "base_url": "https://www.magenfinancial.com/careers",
        "search_url": "https://www.magenfinancial.com/careers",
    },
    {
        "name": "Generali Investments",
        "scraper_type": "custom_html",
        "base_url": "https://www.generali-investments.com/careers",
        "search_url": "https://www.generali-investments.com/careers",
    },
    {
        "name": "Deutsche Pfandbriefbank",
        "scraper_type": "custom_html",
        "base_url": "https://www.pfandbriefbank.com/en/careers.html",
        "search_url": "https://www.pfandbriefbank.com/en/careers.html",
    },
    {
        "name": "China Merchants Securities",
        "scraper_type": "custom_html",
        "base_url": "https://www.cmschina.com/en/careers",
        "search_url": "https://www.cmschina.com/en/careers",
    },
    {
        "name": "Groupe BPCE",
        "scraper_type": "custom_html",
        "base_url": "https://groupebpce.com/carrieres",
        "search_url": "https://groupebpce.com/carrieres",
    },
]
