# Primary role keywords - Finance de Marché only
ROLE_KEYWORDS = [
    "trading",
    "sales",
    "structuration",
    "structuring",
    "derivatives",
    "fixed income",
    "quantitative analyst",
    "quant",
    "risk management",
    "market risk",
    "structured products",
    "rates",
    "credit",
    "equity derivatives",
    "flow trading",
    "exotic",
    "global markets",
    "capital markets",
    "commodities",
    "FX",
    "forex",
    "interest rate",
    "volatility",
    "pricing",
    "front office",
    "middle office",
    "market making",
    "electronic trading",
    "algo trading",
    "delta one",
]

# Internship-type identifiers
# NOTE: alternance is EXCLUDED on purpose (user does not want alternance)
INTERNSHIP_PREFIXES_FR = ["stage", "stagiaire", "cesure", "césure"]
INTERNSHIP_PREFIXES_EN = ["internship", "intern", "placement", "graduate program", "summer analyst"]

# Duration filter patterns (regex) - only 6-month internships
DURATION_PATTERNS = [
    r"6\s*mois",
    r"6\s*months?",
    r"six\s*months?",
    r"six\s*mois",
    r"cesure",
    r"césure",
    r"gap\s*year",
    r"ann[ée]e\s*de\s*c[ée]sure",
    r"long\s*internship",
    r"4\s*to\s*6\s*months?",
    r"4\s*[àa]\s*6\s*mois",
    r"5\s*[àa]\s*6\s*mois",
]

# Duration patterns to EXCLUDE (12-month stages, alternance)
EXCLUDE_DURATION_PATTERNS = [
    r"12\s*mois",
    r"12\s*months?",
    r"twelve\s*months?",
    r"1\s*an\b",
    r"1\s*year",
    r"one\s*year",
    r"24\s*mois",
    r"18\s*mois",
    r"alternance",
    r"apprenti",
    r"contrat\s*pro",
    r"contrat\s*d.apprentissage",
]

# Negative keywords (filter out irrelevant results) - applied to TITLE
EXCLUDE_KEYWORDS = [
    # Seniority / permanent roles
    "CDI",
    "CDD",
    "permanent",
    "experienced",
    "senior",
    "manager",
    "director",
    "VP",
    "vice president",
    "head of",
    "managing director",
    "executive",
    "principal",
    "full-time",
    "full time",
    "temps plein",
    "freelance",
    "consultant",
    "contractor",
    "intérimaire",
    "interim",
    # NOTE: "analyst" and "associate" are NOT excluded because
    # "Summer Analyst" and "Summer Associate" are valid internship titles
    # Roles with experience required (not internships)
    "1-3 ans",
    "1-3 years",
    "2-5 years",
    "3+ years",
    "5+ years",
    "10+ years",
    "expérience requise",
    "expérience souhaitée",
    "years of experience",
    "ans d'expérience",
    # M&A / Private Equity / Corporate Finance - NOT finance de marché
    "M&A",
    "mergers",
    "acquisitions",
    "private equity",
    "leveraged finance",
    "corporate finance",
    "corporate banking",
    "investment banking",
    "advisory",
    "ECM",
    "DCM",
    # Alternance
    "alternance",
    "alternant",
    "apprenti",
    "contrat pro",
    "contrat d'apprentissage",
    "professionnalisation",
    # VIE (not a stage)
    "V.I.E",
    "VIE",
    "volontariat international",
]

# Companies/sectors to exclude from results (non-finance-de-marché)
EXCLUDE_COMPANIES = [
    # Retail / Fashion / Luxury
    "claire's",
    "galeries lafayette",
    "galerie lafayette",
    "l'oreal",
    "l'oréal",
    "loreal",
    "lvmh",
    "kering",
    "hermes",
    "hermès",
    "chanel",
    "dior",
    "gucci",
    "sephora",
    "zara",
    "h&m",
    "primark",
    "mango",
    "uniqlo",
    "nike",
    "adidas",
    "puma",
    "asos",
    "zalando",
    "vuitton",
    "balenciaga",
    "saint laurent",
    "bottega veneta",
    "cartier",
    "tiffany",
    "burberry",
    "prada",
    # Supermarkets / FMCG
    "carrefour",
    "auchan",
    "leclerc",
    "danone",
    "nestle",
    "nestlé",
    "procter",
    "unilever",
    "coca cola",
    "pepsi",
    "mondelez",
    "kraft",
    "colgate",
    "henkel",
    "reckitt",
    "mars inc",
    "ferrero",
    "lidl",
    "aldi",
    "intermarché",
    "intermarche",
    "casino",
    "monoprix",
    "franprix",
    # Sports / Home / DIY
    "decathlon",
    "ikea",
    "leroy merlin",
    "castorama",
    "brico",
    # Tech (not finance)
    "amazon",
    "apple",
    "google",
    "microsoft",
    "salesforce",
    "sap",
    "oracle",
    "meta",
    "facebook",
    "uber",
    "airbnb",
    "booking.com",
    "spotify",
    "netflix",
    "tesla",
    # Consulting / Audit (not finance de marché)
    "accenture",
    "capgemini",
    "deloitte",
    "pwc",
    "kpmg",
    "ey ",
    "ernst & young",
    "mckinsey",
    "bain",
    "bcg",
    "oliver wyman",
    "roland berger",
    "simon kucher",
    "wavestone",
    "sia partners",
    # NGOs / Charities / Associations / Public sector
    "oeuvre de secours",
    "croix rouge",
    "croix-rouge",
    "red cross",
    "médecins sans frontières",
    "medecins sans frontieres",
    "unicef",
    "amnesty",
    "oxfam",
    "secours populaire",
    "secours catholique",
    "emmaüs",
    "emmaus",
    "restos du coeur",
    "restos du cœur",
    "apprentis d'auteuil",
    "fondation",
    "association",
    # Pharma / Healthcare (not finance)
    "sanofi",
    "pfizer",
    "novartis",
    "roche",
    "johnson & johnson",
    "astrazeneca",
    "bayer",
    "merck",
    "abbvie",
    "gsk",
    "glaxo",
    # Telecom / Media (not finance)
    "orange",
    "bouygues telecom",
    "sfr",
    "free mobile",
    "iliad",
    "tf1",
    "canal+",
    "canal plus",
    "vivendi",
    # Energy / Utilities (not finance de marché)
    "edf",
    "engie",
    "total energies",
    "totalenergies",
    "veolia",
    "suez",
    # Transport / Automotive
    "sncf",
    "ratp",
    "air france",
    "airbus",
    "renault",
    "peugeot",
    "stellantis",
    "michelin",
    "valeo",
    # Insurance (not market-facing unless specified)
    "maif",
    "matmut",
    "macif",
    "groupama",
    "mma",
    # Food / Restaurant
    "mcdonald",
    "burger king",
    "starbucks",
    "subway",
    "domino's",
    "paul",
    "flunch",
]

# Non-finance-de-marché title keywords to exclude
EXCLUDE_TITLE_KEYWORDS = [
    "retail sales",
    "commercial",
    "business development",
    "account manager",
    "vente",
    "vendeur",
    "vendeuse",
    "chef de rayon",
    "responsable magasin",
    "store manager",
    "marketing",
    "communication",
    "ressources humaines",
    "human resources",
    "supply chain",
    "logistics",
    "logistique",
    "IT support",
    "helpdesk",
    "comptabilité",
    "accounting",
    "audit",
    "compliance",
    "legal",
    "juridique",
    "relation client",
    "customer service",
    "after sales",
    "après-vente",
    "data engineer",
    "data scientist",
    "software engineer",
    "développeur",
    "developer",
    "devops",
    "social worker",
    "éducateur",
    "educateur",
    "infirmier",
    "aide soignant",
    "aide-soignant",
    "animateur",
    "bénévole",
    "benevole",
    "volunteer",
    "charity",
    "humanitarian",
    "humanitaire",
    "associatif",
    "travailleur social",
    "chef de projet",
    "project manager",
    "product manager",
    "product owner",
    "scrum master",
    "ux designer",
    "ui designer",
    "graphiste",
    "graphic design",
    "content manager",
    "community manager",
    "social media",
    "seo",
    "sea",
]

# Locations to EXCLUDE (secondary French cities)
EXCLUDE_LOCATIONS = [
    "toulouse",
    "lyon",
    "marseille",
    "aix-en-provence",
    "aix en provence",
    "nantes",
    "bordeaux",
    "lille",
    "strasbourg",
    "montpellier",
    "rennes",
    "grenoble",
    "nice",
    "toulon",
    "dijon",
    "clermont-ferrand",
    "clermont ferrand",
    "saint-etienne",
    "saint etienne",
    "reims",
    "rouen",
    "metz",
    "nancy",
    "orleans",
    "orléans",
    "caen",
    "angers",
    "brest",
    "le mans",
    "amiens",
    "limoges",
    "perpignan",
    "poitiers",
    "pau",
    "valence",
]

# Locations to ACCEPT
ACCEPTED_LOCATIONS = [
    # Paris & Île-de-France
    "paris",
    "la defense",
    "la défense",
    "puteaux",
    "courbevoie",
    "levallois",
    "neuilly",
    "issy",
    "boulogne",
    "ile-de-france",
    "île-de-france",
    "idf",
    "92",
    "75",
    # UK - ONLY London and Dublin
    "london",
    "canary wharf",
    "city of london",
    "dublin",
    # Switzerland
    "switzerland",
    "suisse",
    "zurich",
    "zürich",
    "geneva",
    "genève",
    "geneve",
    "bern",
    "basel",
    "bâle",
    # Luxembourg
    "luxembourg",
    # Germany
    "germany",
    "allemagne",
    "frankfurt",
    "francfort",
    "munich",
    "münchen",
    "berlin",
    "hamburg",
    "düsseldorf",
    "dusseldorf",
]

# UK cities to EXCLUDE (everything except London and Dublin)
EXCLUDE_UK_LOCATIONS = [
    "edinburgh",
    "manchester",
    "birmingham",
    "glasgow",
    "leeds",
    "liverpool",
    "bristol",
    "cardiff",
    "belfast",
    "newcastle",
    "sheffield",
    "nottingham",
    "cambridge",
    "oxford",
    "southampton",
    "brighton",
    "reading",
    "bournemouth",
    "aberdeen",
    "cork",
    "galway",
    "limerick",
]
